#
# Copyright (c) 2017 Stratosphere Lab.
# 
# This file is part of ManaTI Project 
# (see <https://stratosphereips.org>). It was created by 'Raul B. Netto <raulbeni@gmail.com>'
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this program. See the file 'docs/LICENSE' or see <http://www.gnu.org/licenses/> 
# for copying permission.
#
# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-21 11:47
from __future__ import unicode_literals

from django.db import migrations, models
from django.core import management


# def run_migrations_background_task(apps, schema_editor):
#     management.call_command("makemigrations", "background_task")
#     management.call_command("migrate", "background_task")

class Migration(migrations.Migration):

    dependencies = [
        ('api_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalmodule',
            name='status',
            field=models.CharField(choices=[('idle', 'idle'), ('running', 'running'), ('removed', 'removed')], default='idle', max_length=20),
        ),
        # migrations.RunPython(run_migrations_background_task),
    ]
