# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-21 11:47
from __future__ import unicode_literals

from django.db import migrations, models
from django.core import management


# def run_migrations_background_task(apps, schema_editor):
#     management.call_command("makemigrations", "background_task")
#     management.call_command("migrate", "background_task")

class Migration(migrations.Migration):

    dependencies = [
        ('api_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalmodule',
            name='status',
            field=models.CharField(choices=[('idle', 'idle'), ('running', 'running'), ('removed', 'removed')], default='idle', max_length=20),
        ),
        # migrations.RunPython(run_migrations_background_task),
    ]
