# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-21 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalmodule',
            name='status',
            field=models.CharField(choices=[('idle', 'idle'), ('running', 'running'), ('removed', 'removed')], default='idle', max_length=20),
        ),
    ]
