# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-09 20:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_manager', '0002_externalmodule_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='externalmodule',
            name='acronym',
        ),
    ]
