# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-02 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_manager', '0003_remove_externalmodule_acronym'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalmodule',
            name='filename',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='externalmodule',
            name='module_instance',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='externalmodule',
            name='module_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='externalmodule',
            name='version',
            field=models.CharField(max_length=30),
        ),
    ]
