# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-28 13:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('manati_ui', '0029_auto_20170627_0944'),
        ('api_manager', '0004_auto_20170302_1352'),
    ]

    operations = [
        migrations.CreateModel(
            name='IOC_WHOIS_RelatedExecuted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created_at')),
                ('updated_at', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='updated_at')),
                ('status', models.CharField(choices=[('finished', 'finished'), ('running', 'running'), ('removed', 'removed'), ('error', 'error')], default='running', max_length=20)),
                ('analysis_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manati_ui.AnalysisSession')),
                ('ioc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manati_ui.IOC')),
            ],
            options={
                'db_table': 'manati_ioc_whois_related_executed',
            },
        ),
    ]
