# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-10-18 22:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_manager', '0005_ioc_whois_relatedexecuted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalmodule',
            name='description',
            field=models.TextField(),
        ),
    ]
