#
# Copyright (c) 2017 Stratosphere Laboratory.
#
# This file is part of ManaTI Project
# (see <https://stratosphereips.org>). It was created by 'Raul B. Netto <raulbeni@gmail.com>'
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. See the file 'docs/LICENSE' or see <http://www.gnu.org/licenses/>
# for copying permission.
#
# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-12 16:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
from manati.analysis_sessions.models import AppParameter


def create_virus_total_api_key(apps, schema_editor):
    AppParameter.objects.create(key=AppParameter.KEY_OPTIONS.virus_total_key_api,
                                value='d65148c145756fe3d093eff9d1630db21bad73895b6bca30839a69e28ab810a2')


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_sessions', '0012_webloghistory_old_verdict'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created_at')),
                ('updated_at', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='updated_at')),
                ('key', models.CharField(choices=[('virus_total_key_api', 'Virus Total Key API')], default='', max_length=20)),
                ('value', models.CharField(default='', max_length=255)),
            ],
            options={
                'db_table': 'manati_app_parameters',
            },
        ),
        migrations.RunPython(create_virus_total_api_key),
    ]
