#
# Copyright (c) 2017 Stratosphere Laboratory.
#
# This file is part of ManaTI Project
# (see <https://stratosphereips.org>). It was created by 'Raul B. Netto <raulbeni@gmail.com>'
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. See the file 'docs/LICENSE' or see <http://www.gnu.org/licenses/>
# for copying permission.
#
# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-27 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_sessions','0028_migrate_weblogs_to_ioc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weblog',
            name='was_whois_related',
        ),
        migrations.RemoveField(
            model_name='weblog',
            name='whois_related_weblogs',
        ),
        migrations.AddField(
            model_name='ioc',
            name='whois_related_iocs',
            field=models.ManyToManyField(related_name='_ioc_whois_related_iocs_+', to='analysis_sessions.IOC'),
        ),
    ]
