# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-08-31 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_sessions', '0032_auto_20170926_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='ioc',
            name='verdict',
            field=models.CharField(choices=[(b'malicious', b'Malicious'), (b'legitimate', b'Legitimate'), (b'suspicious', b'Suspicious'), (b'undefined', b'Undefined'), (b'falsepositive', b'False Positive'), (b'malicious_legitimate', b'Malicious/Legitimate'), (b'suspicious_legitimate', b'Suspicious/Legitimate'), (b'undefined_legitimate', b'Undefined/Legitimate'), (b'falsepositive_legitimate', b'False Positive/Legitimate'), (b'undefined_malicious', b'Undefined/Malicious'), (b'suspicious_malicious', b'Suspicious/Malicious'), (b'falsepositive_malicious', b'False Positive/Malicious'), (b'falsepositive_suspicious', b'False Positive/Suspicious'), (b'undefined_suspicious', b'Undefined/Suspicious'), (b'undefined_falsepositive', b'Undefined/False Positive')], default=b'undefined', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='analysissession',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('removed', 'Removed')], default='open', max_length=30),
        ),
        migrations.AlterField(
            model_name='analysissession',
            name='type_file',
            field=models.CharField(choices=[('bro_http_log', 'BRO weblogs http.log'), ('cisco_file', 'CISCO weblogs Specific File'), ('apache_http_log', 'Apache logs'), ('binetflow', 'Argus bidirectional netflows'), ('uninetflow', 'Argus unidirectional netflows')], default='cisco_file', max_length=50),
        ),
    ]
