# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-08-31 15:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_sessions', '0032_auto_20170926_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='ioc',
            name='verdict',
            field=models.CharField(choices=[(b'malicious', b'Malicious'), (b'legitimate', b'Legitimate'), (b'suspicious', b'Suspicious'), (b'undefined', b'Undefined'), (b'falsepositive', b'False Positive'), (b'malicious_legitimate', b'Malicious/Legitimate'), (b'suspicious_legitimate', b'Suspicious/Legitimate'), (b'undefined_legitimate', b'Undefined/Legitimate'), (b'falsepositive_legitimate', b'False Positive/Legitimate'), (b'undefined_malicious', b'Undefined/Malicious'), (b'suspicious_malicious', b'Suspicious/Malicious'), (b'falsepositive_malicious', b'False Positive/Malicious'), (b'falsepositive_suspicious', b'False Positive/Suspicious'), (b'undefined_suspicious', b'Undefined/Suspicious'), (b'undefined_falsepositive', b'Undefined/False Positive')], default=b'undefined', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='analysissession',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('removed', 'Removed')], default='open', max_length=30),
        ),
        migrations.AlterField(
            model_name='analysissession',
            name='type_file',
            field=models.CharField(choices=[('bro_http_log', 'BRO weblogs http.log'), ('cisco_file', 'CISCO weblogs Specific File'), ('apache_http_log', 'Apache logs'), ('binetflow', 'Argus bidirectional netflows'), ('uninetflow', 'Argus unidirectional netflows')], default='cisco_file', max_length=50),
        ),
        migrations.CreateModel(
            name='IOCHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False,
                                                                   verbose_name='created_at')),
                ('updated_at',
                 model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False,
                                                          verbose_name='updated_at')),
                ('version', models.IntegerField(default=0, editable=False)),
                ('verdict', models.CharField(choices=[(b'malicious', b'Malicious'), (b'legitimate', b'Legitimate'),
                                                      (b'suspicious', b'Suspicious'), (b'undefined', b'Undefined'),
                                                      (b'falsepositive', b'False Positive'),
                                                      (b'malicious_legitimate', b'Malicious/Legitimate'),
                                                      (b'suspicious_legitimate', b'Suspicious/Legitimate'),
                                                      (b'undefined_legitimate', b'Undefined/Legitimate'),
                                                      (b'falsepositive_legitimate', b'False Positive/Legitimate'),
                                                      (b'undefined_malicious', b'Undefined/Malicious'),
                                                      (b'suspicious_malicious', b'Suspicious/Malicious'),
                                                      (b'falsepositive_malicious', b'False Positive/Malicious'),
                                                      (b'falsepositive_suspicious', b'False Positive/Suspicious'),
                                                      (b'undefined_suspicious', b'Undefined/Suspicious'),
                                                      (b'undefined_falsepositive', b'Undefined/False Positive')],
                                             default=b'undefined', max_length=50)),
                ('old_verdict', models.CharField(choices=[(b'malicious', b'Malicious'), (b'legitimate', b'Legitimate'),
                                                          (b'suspicious', b'Suspicious'), (b'undefined', b'Undefined'),
                                                          (b'falsepositive', b'False Positive'),
                                                          (b'malicious_legitimate', b'Malicious/Legitimate'),
                                                          (b'suspicious_legitimate', b'Suspicious/Legitimate'),
                                                          (b'undefined_legitimate', b'Undefined/Legitimate'),
                                                          (b'falsepositive_legitimate', b'False Positive/Legitimate'),
                                                          (b'undefined_malicious', b'Undefined/Malicious'),
                                                          (b'suspicious_malicious', b'Suspicious/Malicious'),
                                                          (b'falsepositive_malicious', b'False Positive/Malicious'),
                                                          (b'falsepositive_suspicious', b'False Positive/Suspicious'),
                                                          (b'undefined_suspicious', b'Undefined/Suspicious'),
                                                          (b'undefined_falsepositive', b'Undefined/False Positive')],
                                                 default=b'undefined', max_length=50)),
                ('description', models.CharField(default='', max_length=255, null=True)),
                ('object_id', models.CharField(max_length=20)),
                ('content_type',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('ioc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories',
                                          to='analysis_sessions.IOC')),
            ],
            options={
                'db_table': 'manati_ioc_history',
            },
        ),
        migrations.AlterUniqueTogether(
            name='iochistory',
            unique_together=set([('version', 'ioc')]),
        ),
    ]
