# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-11-01 17:28
from __future__ import unicode_literals

from django.db import migrations, models
import encrypted_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='threshold_whois_distance',
            field=models.IntegerField(default=75, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='passivetotal_user',
            field=encrypted_fields.fields.EncryptedEmailField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='privacy',
            field=models.CharField(choices=[(b'open', 'Open'), (b'registered', 'Registered'), (b'closed', 'Closed')], default=b'closed', help_text='Designates who can view your profile.', max_length=15, verbose_name='privacy'),
        ),
    ]
