# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-27 22:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Name by Default', max_length=200)),
                ('created_at', models.TimeField(auto_now_add=True)),
                ('updated_at', models.TimeField(auto_now=True)),
            ],
            options={
                'db_table': 'manati_analysis_sessions',
            },
        ),
        migrations.CreateModel(
            name='Weblog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=200, null=True)),
                ('http_url', models.URLField(max_length=255, null=True)),
                ('http_status', models.CharField(max_length=30, null=True)),
                ('endpoints_server', models.CharField(max_length=100, null=True)),
                ('transfer_upload', models.IntegerField(null=True)),
                ('transfer_download', models.IntegerField(null=True)),
                ('time_duration', models.CharField(max_length=200, null=True)),
                ('http_referer', models.CharField(max_length=200, null=True)),
                ('http_userAgent', models.CharField(max_length=200, null=True)),
                ('contentType_fromHttp', models.CharField(max_length=200, null=True)),
                ('user_name', models.CharField(max_length=200, null=True)),
                ('verdict', models.CharField(choices=[('normal', 'normal'), ('malicious', 'malicious'), ('legitimate', 'legitimate'), ('suspicious', 'suspicious'), ('false_positive', 'False Positive')], default='normal', max_length=20)),
                ('created_at', models.TimeField(auto_now_add=True)),
                ('updated_at', models.TimeField(auto_now=True)),
                ('analysis_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manati_ui.AnalysisSession')),
            ],
            options={
                'db_table': 'manati_weblogs',
            },
        ),
    ]
