# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-17 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manati_ui', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weblog',
            name='verdict',
            field=models.CharField(choices=[('malicious', 'malicious'), ('legitimate', 'legitimate'), ('suspicious', 'suspicious'), ('false_positive', 'False Positive')], default='legitimate', max_length=20),
        ),
    ]
