# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-21 15:43
from __future__ import unicode_literals

from django.db import migrations, models
import django_enumfield.db.fields
import manati_ui.models


class Migration(migrations.Migration):

    dependencies = [
        ('manati_ui', '0003_auto_20160817_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weblog',
            name='contentType_fromHttp',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='weblog',
            name='http_referer',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='weblog',
            name='http_url',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='weblog',
            name='http_userAgent',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='weblog',
            name='register_status',
            field=django_enumfield.db.fields.EnumField(default=0, enum=manati_ui.models.RegisterStatus, null=True),
        ),
        migrations.AlterField(
            model_name='weblog',
            name='time_duration',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='weblog',
            name='user_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='weblog',
            name='verdict',
            field=models.CharField(choices=[('malicious', 'Malicious'), ('legitimate', 'Legitimate'), ('suspicious', 'Suspicious'), ('undefined', 'Undefined'), ('false_positive', 'False Positive'), ('malicious_legitimate', 'Malicious/Legitimate'), ('suspicious_legitimate', 'Suspicious/Legitimate'), ('undefined_legitimate', 'Undefined/Legitimate'), ('false_positive_legitimate', 'False Positive/Legitimate'), ('undefined_malicious', 'Undefined/Malicious'), ('suspicious_malicious', 'Suspicious/Malicious'), ('false_positive_malicious', 'False Positive/Malicious'), ('false_positive_suspicious', 'False Positive/Suspicious'), ('undefined_suspicious', 'Undefined/Suspicious'), ('undefined_false_positive', 'Undefined/False Positive')], default='legitimate', max_length=20, null=True),
        ),
    ]
