# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-23 17:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields
import model_utils.fields



class Migration(migrations.Migration):
    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manati_ui', '0006_auto_20160923_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weblog',
            name='contentType_fromHttp',
        ),
        migrations.RemoveField(
            model_name='weblog',
            name='endpoints_server',
        ),
        migrations.RemoveField(
            model_name='weblog',
            name='http_referer',
        ),
        migrations.RemoveField(
            model_name='weblog',
            name='http_status',
        ),
        migrations.RemoveField(
            model_name='weblog',
            name='http_url',
        ),
        migrations.RemoveField(
            model_name='weblog',
            name='http_userAgent',
        ),
        migrations.RemoveField(
            model_name='weblog',
            name='time',
        ),
        migrations.RemoveField(
            model_name='weblog',
            name='time_duration',
        ),
        migrations.RemoveField(
            model_name='weblog',
            name='transfer_download',
        ),
        migrations.RemoveField(
            model_name='weblog',
            name='transfer_upload',
        ),
        migrations.RemoveField(
            model_name='weblog',
            name='user_name',
        ),

    ]
