# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-27 12:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manati_ui', '0007_auto_20160923_1716'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
    ]
