#
# Copyright (c) 2017 Stratosphere Lab.
# 
# This file is part of ManaTI Project 
# (see <https://stratosphereips.org>). It was created by 'Raul B. Netto <raulbeni@gmail.com>'
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this program. See the file 'docs/LICENSE' or see <http://www.gnu.org/licenses/> 
# for copying permission.
#
# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-29 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manati_ui', '0009_auto_20160927_1438'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webloghistory',
            old_name='new_verdict',
            new_name='verdict',
        ),
        migrations.AddField(
            model_name='webloghistory',
            name='version',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='webloghistory',
            name='description',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.RemoveField(
            model_name='webloghistory',
            name='old_verdict',
        ),
        migrations.AlterUniqueTogether(
            name='webloghistory',
            unique_together=set([('version', 'weblog')]),
        ),
    ]
