# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-29 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manati_ui', '0009_auto_20160927_1438'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webloghistory',
            old_name='new_verdict',
            new_name='verdict',
        ),
        migrations.AddField(
            model_name='webloghistory',
            name='version',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='webloghistory',
            name='description',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.RemoveField(
            model_name='webloghistory',
            name='old_verdict',
        ),
        migrations.AlterUniqueTogether(
            name='webloghistory',
            unique_together=set([('version', 'weblog')]),
        ),
    ]
