# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-20 11:48
from __future__ import unicode_literals

from django.db import migrations, models
# from django.contrib.auth.models import User, AnonymousUser
from django.contrib.auth.hashers import make_password
import datetime
import json


def create_anonymous_user_for_metrics(apps, schema_editor):
    User = apps.get_registered_model('auth', 'User')
    if not User.objects.filter(username='anonymous_user_for_metrics').exists():
        anonymous = User(
            username='anonymous_user_for_metrics',
            email='anonymous_user@admin.com',
            password=make_password('user for metrics'),
            is_superuser=False,
            last_login=datetime.datetime.now(),
            is_staff=False,
        )
        anonymous.save()


class Migration(migrations.Migration):

    dependencies = [
        ('manati_ui', '0017_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysissession',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(create_anonymous_user_for_metrics),
    ]
