#
# Copyright (c) 2017 Stratosphere Laboratory.
# 
# This file is part of ManaTI Project 
# (see <https://stratosphereips.org>). It was created by 'Raul B. Netto <raulbeni@gmail.com>'
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this program. See the file 'docs/LICENSE' or see <http://www.gnu.org/licenses/> 
# for copying permission.
#
# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-20 11:48
from __future__ import unicode_literals

from django.db import migrations, models
# from django.contrib.auth.models import User, AnonymousUser
from django.contrib.auth.hashers import make_password
import datetime
import json


def create_anonymous_user_for_metrics(apps, schema_editor):
    User = apps.get_registered_model('auth', 'User')
    if not User.objects.filter(username='anonymous_user_for_metrics').exists():
        anonymous = User(
            username='anonymous_user_for_metrics',
            email='anonymous_user@admin.com',
            password=make_password('user for metrics'),
            is_superuser=False,
            last_login=datetime.datetime.now(),
            is_staff=False,
        )
        anonymous.save()


class Migration(migrations.Migration):

    dependencies = [
        ('manati_ui', '0017_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysissession',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(create_anonymous_user_for_metrics),
    ]
