# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-20 09:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('manati_ui', '0017_comment_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhoisRelatedWeblog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created_at')),
                ('updated_at', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='updated_at')),
                ('weblog_domain_a', models.ForeignKey(db_column='weblog_domain_b', on_delete=django.db.models.deletion.CASCADE, related_name='weblog_domain_b', to='manati_ui.Weblog')),
            ],
            options={
                'db_table': 'manati_whois_related_weblogs',
            },
        ),
        migrations.AlterField(
            model_name='webloghistory',
            name='weblog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='manati_ui.Weblog'),
        ),
        migrations.AddField(
            model_name='weblog',
            name='whois_related_weblogs',
            field=models.ManyToManyField(related_name='_weblog_whois_related_weblogs_+', through='manati_ui.WhoisRelatedWeblog', to='manati_ui.Weblog'),
        ),
    ]
