# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-21 09:06
from __future__ import unicode_literals
from bulk_update.helper import bulk_update

from django.db import migrations, models
from manati_ui.models import Weblog,AnalysisSession


def add_type_file_all_analysis_session(apps, schema_editor):
    # AnalysisSession = apps.get_registered_model('manati_ui', 'AnalysisSession')
    ass = AnalysisSession.objects.all()
    for analysis_session in ass:
        id = analysis_session.weblog_set.first().id
        attr = Weblog.objects.get(id=id).attributes_obj
        if AnalysisSession.INFO_ATTRIBUTES['cisco_file']['url'] in attr.keys():
            analysis_session.type_file = AnalysisSession.TYPE_FILES.cisco_file
        elif AnalysisSession.INFO_ATTRIBUTES['bro_http_log']['url'] in attr.keys():
            analysis_session.type_file = AnalysisSession.TYPE_FILES.bro_http_log

    bulk_update(ass)


class Migration(migrations.Migration):

    dependencies = [
        ('manati_ui', '0019_whois_related_weblog'),
    ]

    operations = [
        migrations.RunPython(add_type_file_all_analysis_session),

    ]
