# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-21 09:06
from __future__ import unicode_literals
from bulk_update.helper import bulk_update

from django.db import migrations, models, connection
from manati_ui.models import Weblog,AnalysisSession
import json


def dictfetchall(cursor):
    "Return all rows from a cursor as a dict"
    columns = [col[0] for col in cursor.description]
    return [
        dict(zip(columns, row))
        for row in cursor.fetchall()
    ]


def get_all_weblogs_by_analysis_session(self, analysis_session_id=None):
    with connection.cursor() as cursor:
        if analysis_session_id:
            cursor.execute("SELECT * FROM manati_weblogs WHERE analysis_session_id = %s", [analysis_session_id])
        else:
            cursor.execute("SELECT * FROM manati_weblogs")
        row = dictfetchall(cursor)
    return row

def add_type_file_all_analysis_session(apps, schema_editor):
    # AnalysisSession = apps.get_registered_model('manati_ui', 'AnalysisSession')
    ass = AnalysisSession.objects.all()
    for analysis_session in ass:
        attr = get_all_weblogs_by_analysis_session(analysis_session.id)[0]['attributes']
        if attr:
            if not type(attr) == dict:
                attr = json.loads(attr)
        else:
            attr = json.loads({})
        if AnalysisSession.INFO_ATTRIBUTES['cisco_file']['url'] in attr.keys():
            analysis_session.type_file = AnalysisSession.TYPE_FILES.cisco_file
        elif AnalysisSession.INFO_ATTRIBUTES['bro_http_log']['url'] in attr.keys():
            analysis_session.type_file = AnalysisSession.TYPE_FILES.bro_http_log

    bulk_update(ass)


class Migration(migrations.Migration):

    dependencies = [
        ('manati_ui', '0019_whois_related_weblog'),
    ]

    operations = [
        migrations.RunPython(add_type_file_all_analysis_session),

    ]
