# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-22 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manati_ui', '0020_type_file_migration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weblog',
            name='whois_related_weblogs',
        ),
        migrations.RemoveField(
            model_name='whoisrelatedweblog',
            name='weblog_domain_a',
        ),
        migrations.DeleteModel(
            name='WhoisRelatedWeblog',
        ),
        migrations.AddField(
            model_name='weblog',
            name='whois_related_weblogs',
            field=models.ManyToManyField(related_name='_weblog_whois_related_weblogs_+', to='manati_ui.Weblog'),
        ),

    ]
