# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-03 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manati_ui', '0021_fixing_whois_related_attribute'),
    ]

    operations = [
        migrations.AddField(
            model_name='weblog',
            name='was_whois_related',
            field=models.BooleanField(default=False),
        ),
    ]
