# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-26 15:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('manati_ui', '0026_whoisconsult'),
    ]

    operations = [
        migrations.CreateModel(
            name='IOC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created_at')),
                ('updated_at', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='updated_at')),
                ('value', models.CharField(max_length=256, unique=True)),
                ('ioc_type', models.CharField(choices=[('domain', 'Domain Name'), ('ip', 'IP Address')], max_length=20)),
                ('weblogs', models.ManyToManyField(to='manati_ui.Weblog')),
            ],
            options={
                'db_table': 'manati_indicators_of_compromise',
            },
        ),
    ]
