# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-08 11:33
from __future__ import unicode_literals

from django.db import migrations, models
import datetime


def create_admin_users(apps, schema_editor):
    User = apps.get_registered_model('auth', 'User')
    admin1 = User(
        username='seba',
        email='eldraco@gmail.com',
        password='sebapassword2017',
        is_superuser=True,
        last_login=datetime.datetime.now(),
        is_staff=True
    )
    admin1.save()
    admin2 = User(
        username='raul',
        email='raulbeni@gmail.com',
        password='raulpassword2017',
        is_superuser=True,
        last_login=datetime.datetime.now(),
        is_staff=True
    )
    admin2.save()

#create super users for intances
class Migration(migrations.Migration):

    dependencies = [
        ('manati_ui', '0026_whoisconsult'),
    ]

    operations = [
        migrations.RunPython(create_admin_users),
    ]
