# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-27 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manati_ui', '0028_migrate_weblogs_to_ioc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weblog',
            name='was_whois_related',
        ),
        migrations.RemoveField(
            model_name='weblog',
            name='whois_related_weblogs',
        ),
        migrations.AddField(
            model_name='ioc',
            name='whois_related_iocs',
            field=models.ManyToManyField(related_name='_ioc_whois_related_iocs_+', to='manati_ui.IOC'),
        ),
    ]
