# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-09-26 15:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manati_ui', '0029_auto_20170627_0944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ioc',
            name='whois_related_iocs',
        ),
        migrations.RunSQL('DROP TABLE IF EXISTS manati_indicators_of_compromise_whois_related_iocs;'),

    ]
