# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-09-26 15:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('manati_ui', '0030_auto_20170926_1740'),
    ]

    operations = [

        migrations.CreateModel(
            name='WHOISRelatedIOC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created_at')),
                ('updated_at', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='updated_at')),
                ('features_description', jsonfield.fields.JSONField(default=b'{}', null=True)),
                ('numeric_distance', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'manati_indicators_of_compromise_whois_related_iocs',
            },
        ),
    ]
