#
# Copyright (c) 2017 Stratosphere Lab.
# 
# This file is part of ManaTI Project 
# (see <https://stratosphereips.org>). It was created by 'Raul B. Netto <raulbeni@gmail.com>'
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this program. See the file 'docs/LICENSE' or see <http://www.gnu.org/licenses/> 
# for copying permission.
#
# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-09-26 15:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('manati_ui', '0031_auto_20170926_1740'),
    ]

    operations = [

        migrations.AddField(
            model_name='whoisrelatedioc',
            name='from_ioc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_ioc_id',
                                    to='manati_ui.IOC'),
        ),
        migrations.AddField(
            model_name='whoisrelatedioc',
            name='to_ioc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_ioc_id',
                                    to='manati_ui.IOC'),
        ),

        migrations.AddField(
            model_name='ioc',
            name='whois_related_iocs',
            field=models.ManyToManyField(through='manati_ui.WHOISRelatedIOC', to='manati_ui.IOC'),
        ),
    ]
