# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-09-26 15:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('manati_ui', '0031_auto_20170926_1740'),
    ]

    operations = [

        migrations.AddField(
            model_name='whoisrelatedioc',
            name='from_ioc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_ioc_id',
                                    to='manati_ui.IOC'),
        ),
        migrations.AddField(
            model_name='whoisrelatedioc',
            name='to_ioc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_ioc_id',
                                    to='manati_ui.IOC'),
        ),

        migrations.AddField(
            model_name='ioc',
            name='whois_related_iocs',
            field=models.ManyToManyField(through='manati_ui.WHOISRelatedIOC', to='manati_ui.IOC'),
        ),
    ]
