# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-11-28 10:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_manager', '0006_auto_20171019_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ioc_whois_relatedexecuted',
            name='ioc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whois_relation_executions', to='analysis_sessions.IOC'),
        ),
    ]
